org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
org.gradle.vfs.watch=false
org.gradle.daemon=false
